[font]
size = 14.0
builtin_box_drawing = true

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"
style = "Bold Italic"
