#  _   _                  _                 _
# | | | |_   _ _ __  _ __| | __ _ _ __   __| |
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
# |  _  | |_| | |_) | |  | | (_| | | | | (_| |
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#        |___/|_|
#

# Default Configs
$configs = $HOME/.config/hypr/configs

# -----------------------------------------------------
# Monitor
# -----------------------------------------------------
source = $configs/monitor.conf

# -----------------------------------------------------
# Cursor
# -----------------------------------------------------
source = $configs/cursor.conf

# -----------------------------------------------------
# Environment
# -----------------------------------------------------
source = $configs/environment.conf

# -----------------------------------------------------
# Keyboard
# -----------------------------------------------------
source = $configs/keyboard.conf

# -----------------------------------------------------
# Autostart
# -----------------------------------------------------
source = $configs/autostart.conf

# -----------------------------------------------------
# Load configuration files
# -----------------------------------------------------
source = $configs/window.conf
source = $configs/decoration.conf
source = $configs/layout.conf
source = $configs/misc.conf
source = $configs/keybinds.conf
source = $configs/windowrules.conf

# -----------------------------------------------------
# Animation and Gestures
# -----------------------------------------------------
source = $configs/animation.conf

# -----------------------------------------------------
# Environment for xdg-desktop-portal-hyprland
# -----------------------------------------------------
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
