# -----------------------------------------------------
# Source animations
# https://wiki.hypr.land/Configuring/Animations/
# -----------------------------------------------------

source = ~/.config/hypr/configs/animations/default.conf
