# -----------------------------------------------------
# Misc settings
# -----------------------------------------------------

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    mouse_move_enables_dpms = true
    vrr = 2
    enable_swallow = true
    focus_on_activate = false
    swallow_regex = ^(kitty)$
    #disable_autoreload = true
}
