# -----------------------------------------------------
# Monitor Setup
# https://wiki.hypr.land/Configuring/Monitors/#general
# -----------------------------------------------------

monitor=,1920x1080,auto,1
