# startup apps
exec-once = waybar &
# exec-once = nm-applet --indicator &
exec-once = swaync &
# exec-once = hypridle &
exec-once = hyprpaper &

#clipboard manager
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
